spring:
  profiles.active: local  
---
  
spring:
  profiles: local
  datasource:
   driverClassName: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521:dev
   username: ticketing
   password: d1t1b1se
    
server:
  port: 8092
logging:
  level:
    com.emc.eve: INFO
---
spring:
  profiles: cloud
  

---
db:
 postgre:
    DB_URL: jdbc:oracle:thin:@localhost:1521:dev
    DB_USER: ticketing
    DB_PASSWORD: d1t1b1se
---
db1:
 postgre:   
    QA_DB_URL: jdbc:oracle:thin:@localhost:1521:dev
    QA_DB_USER: ticketing_meta
    QA_DB_PASSWORD: d1t1b1se
    
db2:
 mysql:   
    MY_DB_URL: jdbc:mysql://localhost:3306/mahesh
    MY_DB_USER: root
    MY_DB_PASSWORD: root
    
servicenow:
  updateurl : https://dev53134.service-now.com/api/now/table/incident/
  geturl : https://dev53134.service-now.com/api/now/table/incident?number=
  createurl : https://dev53134.service-now.com/api/now/table/incident
  downloadattachement : https://dev53134.service-now.com/api/now/attachment?table_sys_id=
  accept : application/json
  contenttype : application/json
  authorization : Basic YWRtaW46SmV2aWthQDEyMw==
csvList:
  customDateFormatsSupported: dd/MM/yyyy HH:mm:ss.SSSSSSS
#errors:
 #lookup:
  #unknown: testttt
  
   
  